# @name GET请求
GET http://localhost:3000/api/v1/hello
Accept: application/json
###

# @name GET请求
GET http://localhost:3000/?name=jack&pass=啥密码
Accept: application/json
###

# @name POST请求
POST http://localhost:3000/
Content-Type: application/json

{}
###
