# @name GET请求
GET http://localhost:3000/v1/user/hello
Accept: application/json
Authorization: 123
###

# @name GET请求
GET http://localhost:3000/?name=jack&pass=啥密码
Accept: application/json
###

# @name 登录
POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
  "username": "lewin",
  "password": "123456"
}
###

# @name 用户注册
POST http://localhost:3000/v1/user/register
Content-Type: application/json

{
  "username": "lewin",
  "email": "lewinloo0320@gmail.com",
  "password": "123456",
  "code": "050412"
}
###

# @name 获取验证码
POST http://localhost:3000/v1/user/authCode
Content-Type: application/json

{
  "email": "lewinloo0320@gmail.com"
}
###
