# 配置文件

# ---------------------------------------------
# 开发环境、测试环境
env_test:
  # 运行端口配置
  port: ":3000"

  # mysql配置
  mysql:
    addr: ""
    port: ""
    user: ""
    pass: ""
    base: ""

  # mongo配置
  mongo:
    addr: ""
    port: ""
    base: ""

# ---------------------------------------------
# 生产环境
env_prod:
  # 运行端口配置
  port: ":3000"

  # mysql配置
  mysql:
    addr: ""
    port: ""
    user: ""
    pass: ""
    base: ""

  # mongo配置
  mongo:
    addr: ""
    port: ""
    base: ""