# 配置文件

# ---------------------------------------------
# 运行端口配置
port: ":3000"

# redis配置
redis:
  addr: "localhost"
  port: "6379"
  auth: "redis12345"

# mongo配置
mongo:
  addr: "localhost"
  port: "27017"
  base: "resume"

email:
  host: "smtp.163.com"
  port: "25"
  user: ""
  pass: ""

# jwt 配置
jwt:
  secret: "xxxxxx"
  ex: 8
  issuer: "xxx"
  subject: "xxx"
  whiteList: ["/", "/v1/user/login", "/v1/user/reigster", "/v1/user/authCode"]
